project:
  name: Don Leonard
  description: ''
  tools: []
  current_focus: ''
  needs: []
  links:
    docs: ''
    staging: ''
    production: ''
  team:
    lead: bioticinteractions
    contributors:
    - pauldingus
    - jrichardh94
    - jjackson12
  campaign:
    candidate: Don Leonard
    office: Ohio US House District 15
  auto_refresh: true
